### ISSUE TITLE
Acess denied issue

### ISSUE THREAD

**Issue by StarBleu1** [ItsShamed/osu-pack-importer#1]
I tried importing my beatmap packs with the program and everytime i'm getting hit with acess denied. Tried running cmd/program as admin and messed around with folder permissions but no success. No idea how i can fix that would u mind pointing me in the right direction even though it is user error and not program issue.
```
E:\Downloads\xd>OsuPackImporter.exe "E:\Downloads\xd\nomod consistency pack" -v
INFO: Importing archive E:\Downloads\xd\nomod consistency pack

Unhandled exception. System.UnauthorizedAccessException: Access to the path 'E:\Downloads\xd\nomod consistency pack' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.OpenRead(String path)
   at OsuPackImporter.Collections.ExtendedCollection..ctor(String path, ProgressContext context)
   at OsuPackImporter.Program.<>c__DisplayClass6_0.<Run>b__0(ProgressContext ctx)
   at Spectre.Console.Progress.<>c__DisplayClass25_0.<Start>b__0(ProgressContext ctx) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 65
   at Spectre.Console.Progress.<>c__DisplayClass27_0.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 98
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 133
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in /_/src/Spectre.Console/Internal/DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync[T](Func`2 action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 116   at Spectre.Console.Progress.StartAsync(Func`2 action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 96
   at Spectre.Console.Progress.Start(Action`1 action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 69
   at OsuPackImporter.Program.Progress(Action`1 action)
   at OsuPackImporter.Program.Run(Options options)
   at OsuPackImporter.Program.<>c.<Main>b__4_0(Options o)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at OsuPackImporter.Program.Main(String[] args)
```

**Comment by ItsShamed** [comment]
From what I can deduce by the filename, you are trying to import a folder?
The program doesn't support importing folders (yet?), I should probably add guards against trying to import folders for the time being.
Try zipping the folder and import that instead.

**Comment by StarBleu1** [comment]
Hmm, ty for the reply, seems to go further now than access denied but still stuck on other error message. I would assume it means beatmap pack is too big ? 
```
E:\Downloads\xd>OsuPackImporter.exe "E:\Downloads\xd\nomod consistency pack.7z"
INFO: Importing archive E:\Downloads\xd\nomod consistency pack.7z

.

Unhandled exception. System.IO.IOException: Stream was too long.
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Strategies.BufferedFileStreamStrategy.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.FileStream.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at OsuPackImporter.Collections.ExtendedCollection.GetArchive(Stream stream)
   at OsuPackImporter.Collections.ExtendedCollection.Parse(ProgressContext context)
   at OsuPackImporter.Collections.ExtendedCollection..ctor(Stream stream, String name, ProgressContext context)
   at OsuPackImporter.Collections.ExtendedCollection..ctor(String path, ProgressContext context)
   at OsuPackImporter.Program.<>c__DisplayClass6_0.<Run>b__0(ProgressContext ctx)
   at Spectre.Console.Progress.<>c__DisplayClass25_0.<Start>b__0(ProgressContext ctx) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 65
   at Spectre.Console.Progress.<>c__DisplayClass27_0.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 98
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 133
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in /_/src/Spectre.Console/Internal/DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync[T](Func`2 action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 116   at Spectre.Console.Progress.StartAsync(Func`2 action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 96
   at Spectre.Console.Progress.Start(Action`1 action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 69
   at OsuPackImporter.Program.Progress(Action`1 action)
   at OsuPackImporter.Program.Run(Options options)
   at OsuPackImporter.Program.<>c.<Main>b__4_0(Options o)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at OsuPackImporter.Program.Main(String[] args)
```

**Comment by ItsShamed** [comment]
For the record, how big the file is?

**Comment by StarBleu1** [comment]
2.87GB uncompressed

**Comment by ItsShamed** [comment]
Yup, that might be it. `MemoryStream` doesn't seem, to support buffers more than 2 GB by default.
I might need to find an alternative to that.
I don't have access to a Windows box as of right now but it could be useful if you could attach your compressed pack (if you can, I don't know GitHub's limitations on file size), so that I could check against it later.

**Comment by StarBleu1** [comment]
https://drive.google.com/file/d/1BHuxOgakjm9iTLro21zJpWE8Oq4mw4Ce/view?usp=sharing
This should work. As for current issue i'm just gonna split the pack in 2 and then merge collections

**Comment by ItsShamed** [comment]
I think the original issue is solved I guess, I'll open a new issue for the file size.
